const Details=[
    {   name:"PINK",
        color:"#FF6663",
        code:"#FF663",
    },
    {   name:"GRAY",
        color:"#333333",
        code:"#333333",
    },
    {   name:"BLACK",
        color:"#000000",
        code:"#000000",
    },
    {   name:"GREEN",
        color:"#38BB14",
        code:"#38BB14",
    },
    {   name:"RED",
        color:"#C90B0B",
        code:"#C90B0B",
    },
    {   name:"ORANGE",
        color:"#FF8000",
        code:"#FF8000",
    },
    {   name:"YELLOW",
        color:"#FFF500",
        code:"#FFF500",
    },
    {   name:"LIGHT GRAY",
        color:"#CCCCCC",
        code:"#CCCCCC",
    },
    {   name:"PURPLE",
        color:"#7E41A2",
        code:"#7E41A2",
    },
    {   name:"BROWN",
        color:"#C14911",
        code:"#C14911",
    },
    
]
export default Details;